# Generated by Django 6.0.6 on 2026-06-09 06:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('meeting_link', models.URLField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.application')),
            ],
            options={
                'db_table': 'interviews',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='InterviewParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_participants', to='interviews.interview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interview_participants',
                'unique_together': {('interview', 'user')},
            },
        ),
        migrations.AddField(
            model_name='interview',
            name='participants',
            field=models.ManyToManyField(related_name='interviews', through='interviews.InterviewParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('written_feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='interviews.interview')),
            ],
            options={
                'db_table': 'evaluations',
                'ordering': ['-created_at'],
                'unique_together': {('interview', 'evaluator')},
            },
        ),
    ]
