# Generated by Django 6.0.6 on 2026-06-09 06:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=100, unique=True)),
                ('sequence_order', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'statuses',
                'ordering': ['sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_match_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('resume_file', models.FileField(upload_to='resumes/')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='candidates.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='jobs.job')),
            ],
            options={
                'db_table': 'applications',
                'ordering': ['-applied_date'],
            },
        ),
        migrations.CreateModel(
            name='AIProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens_used', models.IntegerField(default=0)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('human_override_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_log', to='applications.application')),
            ],
            options={
                'db_table': 'ai_processing_logs',
            },
        ),
        migrations.CreateModel(
            name='ApplicationSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_skills', to='applications.application')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_skills', to='jobs.skill')),
            ],
            options={
                'db_table': 'application_skills',
                'unique_together': {('application', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='application',
            name='extracted_skills',
            field=models.ManyToManyField(related_name='applications', through='applications.ApplicationSkill', to='jobs.skill'),
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_offered', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_start_date', models.DateTimeField()),
                ('is_accepted', models.BooleanField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='applications.application')),
            ],
            options={
                'db_table': 'job_offers',
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_changed', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='applications.application')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_entries', to='applications.status')),
            ],
            options={
                'db_table': 'application_status_history',
                'ordering': ['-date_changed'],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['ai_match_score'], name='application_ai_matc_f4c5da_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['job'], name='application_job_id_c2a30a_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['candidate'], name='application_candida_0452de_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'candidate')},
        ),
        migrations.AddIndex(
            model_name='applicationstatushistory',
            index=models.Index(fields=['application', 'date_changed'], name='application_applica_0cf618_idx'),
        ),
    ]
