# Generated by Django 6.0.6 on 2026-06-22 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_applicationstatushistory_changed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='education_level',
            field=models.CharField(blank=True, help_text='Highest education level extracted from resume by AI.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='years_experience',
            field=models.FloatField(blank=True, help_text='Years of professional experience extracted from resume by AI.', null=True),
        ),
        
    ]
