# Generated by Django 6.0.6 on 2026-06-09 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=200, unique=True)),
                ('email_subject', models.CharField(max_length=300)),
                ('email_body', models.TextField()),
            ],
            options={
                'db_table': 'message_templates',
                'ordering': ['template_name'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('message_content', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='applications.application')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_communications', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communications', to='communications.messagetemplate')),
            ],
            options={
                'db_table': 'communications_log',
                'ordering': ['-sent_date'],
                'indexes': [models.Index(fields=['application', 'sent_date'], name='communicati_applica_720aa9_idx')],
            },
        ),
    ]
